version: '3'
services:
  app:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}-production-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app-api
      SERVICE_TAGS: production
      PHP_OPCACHE_ENABLED: 1
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 0
      PHP_OPCACHE_MAX_ACCELERATED_FILES: 25000
      PHP_OPCACHE_MEMORY_CONSUMPTION: 192
      PHP_OPCACHE_MAX_WASTED_PERCENTAGE: 10
      PHP_OPCACHE_INTERNED_STRINGS_BUFFER: 128
    working_dir: /var/www
    volumes:
      - ./project:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    networks:
      - app-production-ws
  webserver:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-production-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8000"
    volumes:
      - ./project:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-production-ws
    environment:
      - TZ=Asia/Manila
networks:
  app-production-ws:
    driver: bridge
